-- luacheck: globals describe it assert before_each
local Budget = require("99.lsp.budget")
local eq = assert.are.same

describe("Budget", function()
    describe("new", function()
        it("should create budget with default chars_per_token", function()
            local budget = Budget.new(1000)
            eq(4000, budget.max_chars)
            eq(4, budget.chars_per_token)
            eq(0, budget.used_chars)
        end)

        it("should create budget with custom chars_per_token", function()
            local budget = Budget.new(1000, 3)
            eq(3000, budget.max_chars)
            eq(3, budget.chars_per_token)
        end)
    end)

    describe("estimate_tokens", function()
        it("should estimate tokens from text length", function()
            local budget = Budget.new(1000, 4)
            eq(3, budget:estimate_tokens("hello world!"))
        end)

        it("should round up token estimates", function()
            local budget = Budget.new(1000, 4)
            eq(3, budget:estimate_tokens("hello world"))
        end)

        it("should return 0 for empty text", function()
            local budget = Budget.new(1000)
            eq(0, budget:estimate_tokens(""))
            eq(0, budget:estimate_tokens(nil))
        end)
    end)

    describe("can_fit", function()
        it("should return true if text fits", function()
            local budget = Budget.new(100, 1)
            assert.is_true(budget:can_fit("hello"))
        end)

        it("should return false if text exceeds budget", function()
            local budget = Budget.new(1, 1)
            assert.is_false(budget:can_fit("hello"))
        end)

        it("should account for already used budget", function()
            local budget = Budget.new(10, 1)
            budget:consume("first", "hello")
            assert.is_true(budget:can_fit("hi"))
            assert.is_false(budget:can_fit("hello!"))
        end)

        it("should return true for nil text", function()
            local budget = Budget.new(10, 1)
            assert.is_true(budget:can_fit(nil))
        end)
    end)

    describe("consume", function()
        it("should consume budget and track by section", function()
            local budget = Budget.new(100, 1)
            local success = budget:consume("symbols", "hello")
            assert.is_true(success)
            eq(5, budget.used_chars)
            eq(5, budget.sections["symbols"])
        end)

        it("should accumulate consumption in same section", function()
            local budget = Budget.new(100, 1)
            budget:consume("symbols", "hello")
            budget:consume("symbols", "world")
            eq(10, budget.sections["symbols"])
        end)

        it("should track multiple sections", function()
            local budget = Budget.new(100, 1)
            budget:consume("symbols", "hello")
            budget:consume("imports", "world")
            eq(5, budget.sections["symbols"])
            eq(5, budget.sections["imports"])
            eq(10, budget.used_chars)
        end)

        it("should return false if over budget", function()
            local budget = Budget.new(5, 1)
            local success = budget:consume("test", "hello world")
            assert.is_false(success)
            eq(0, budget.used_chars)
        end)

        it("should handle empty text", function()
            local budget = Budget.new(10, 1)
            assert.is_true(budget:consume("test", ""))
            assert.is_true(budget:consume("test", nil))
            eq(0, budget.used_chars)
        end)
    end)

    describe("remaining", function()
        it("should return full budget initially", function()
            local budget = Budget.new(100, 1)
            eq(100, budget:remaining())
        end)

        it("should return remaining after consumption", function()
            local budget = Budget.new(100, 1)
            budget:consume("test", "hello")
            eq(95, budget:remaining())
        end)

        it("should not go negative", function()
            local budget = Budget.new(5, 1)
            budget.used_chars = 10
            eq(0, budget:remaining())
        end)
    end)

    describe("remaining_tokens", function()
        it("should return remaining in token units", function()
            local budget = Budget.new(100, 4)
            budget:consume("test", string.rep("x", 100))
            eq(75, budget:remaining_tokens())
        end)
    end)

    describe("stats", function()
        it("should return comprehensive statistics", function()
            local budget = Budget.new(100, 4)
            budget:consume("symbols", string.rep("x", 100))
            budget:consume("imports", string.rep("y", 50))

            local stats = budget:stats()
            eq(150, stats.used_chars)
            eq(400, stats.max_chars)
            eq(250, stats.remaining_chars)
            eq(100, stats.max_tokens)
            eq(100, stats.sections["symbols"])
            eq(50, stats.sections["imports"])
            assert.is_true(stats.utilization > 0.37 and stats.utilization < 0.38)
        end)
    end)

    describe("reset", function()
        it("should reset all state", function()
            local budget = Budget.new(100, 1)
            budget:consume("test", "hello")
            budget:reset()
            eq(0, budget.used_chars)
            eq({}, budget.sections)
        end)
    end)

    describe("is_exhausted", function()
        it("should return false when budget available", function()
            local budget = Budget.new(100, 1)
            assert.is_false(budget:is_exhausted())
        end)

        it("should return true when budget used up", function()
            local budget = Budget.new(5, 1)
            budget:consume("test", "hello")
            assert.is_true(budget:is_exhausted())
        end)
    end)

    describe("consume_partial", function()
        it("should consume all if fits", function()
            local budget = Budget.new(100, 1)
            local consumed, truncated = budget:consume_partial("test", "hello")
            eq("hello", consumed)
            assert.is_false(truncated)
            eq(5, budget.used_chars)
        end)

        it("should truncate if exceeds budget", function()
            local budget = Budget.new(3, 1)
            local consumed, truncated = budget:consume_partial("test", "hello")
            eq("hel", consumed)
            assert.is_true(truncated)
            eq(3, budget.used_chars)
        end)

        it("should return empty if no budget remaining", function()
            local budget = Budget.new(5, 1)
            budget:consume("first", "hello")
            local consumed, truncated = budget:consume_partial("second", "world")
            eq("", consumed)
            assert.is_true(truncated)
        end)
    end)
end)
